version: "3.8"

# Services
services:
  # NGINX Server
  proxy:
    image: nginx:1.23.3
    container_name: kripto-proxy
    restart: always
    hostname: kripto-proxy-server
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - app-network

  # FastAPI Backend Server
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: kripto-api
    restart: always
    environment:
      API_KEY: ${API_KEY}
    hostname: kripto-api-service
    volumes:
      - ./api:/code
    networks:
      - app-network

  # React Vite Frontend Server
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: kripto-client
    restart: always
    environment:
      VITE_API_KEY: ${API_KEY}
      VITE_API_HOST: ${API_HOST}
      VITE_PORT: ${CLIENT_PORT}
    hostname: kripto-client-service
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - app-network

# Networks
networks:
  app-network:
    driver: bridge
